apiVersion: v1
kind: Pod
metadata:
  labels:
    name: lightedge-testing
  name: lightedge-testing
spec:
  containers:
  - image: utomn0/spider-lightedge-runtime:latest
    name: lightedge
    imagePullPolicy: Always
    volumeMounts:
    - name: lightedge-storage
      mountPath: /root/.helm/config
      subPath: lightedge/helm.kubeconfig
    - name: lightedge-storage
      mountPath: /local_charts
      subPath: lightedge/local_charts
    - name: helm-repos
      mountPath: /root/.config/helm
    - name: runtime-config
      mountPath: /etc/lightedge/runtime.cfg
      subPath: runtime.cfg
  - name: mongo
    image: mongo
    volumeMounts:
    - name: lightedge-storage
      mountPath: /data/db111
      subPath: lightedge/mongo111
  - name: influxdb
    image: influxdb
  volumes:
  - name: lightedge-storage
    persistentVolumeClaim:
      claimName: light-pvc
  - name: helm-repos
    configMap:
      name: helm-repos-testing
  - name: runtime-config
    configMap:
      name: runtime-config-testing

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: lightedge-testing
  name: lightedge-testing-service1
spec:
  type: NodePort
  ports:
  - name: webui
    port: 80
    protocol: TCP
    targetPort: 8888
    nodePort: 31126
  - name: upf-server
    port: 7000
    protocol: TCP
    targetPort: 7000
    nodePort: 32655
  selector:
    name: lightedge-testing
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-repos-testing
data:
  repositories.yaml: |
    apiVersion: ""
    generated: "0001-01-01T00:00:00Z"
    repositories:
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: stable
      password: ""
      url: https://kubernetes-charts.storage.googleapis.com/
      username: ""
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: bitnami
      password: ""
      url: https://charts.bitnami.com/bitnami
      username: ""

---
  #,appmanager,loconfigmanager,instdescmanager (general manager)
apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-config-testing
data:
  runtime.cfg: |
    [general]
    managers=apimanager,servicemanager
    mongodb=mongodb://localhost:27017/lightedge
    logging=/etc/lightedge/logging.cfg

    [apimanager]
    module=empower_core.apimanager.apimanager
    webui=/var/www/lightedge/

    [tsmanager]
    module=empower_core.timeseriesmanager.timeseriesmanager
    database=lightedge

    [servicemanager]
    module=lightedge.managers.servicemanager.servicemanager
