kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: light-pvc
spec:
  storageClassName: manual
  volumeName: light-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
