apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/clm/"


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: log-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  volumeName: log-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
