apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-www-data
  namespace: {{ .Values.namespace }}
data:
   logger_name: " Response Router " #ResponseRouter1/2/3..
   log_level:  "DEBUG"
   api_port: "3000" # port for API svc
   msg_broker_addr_one: "localhost:30072" #"80.159.227.43:31123" # for IT TIM:163.162.42.24
   msg_broker_addr_two: "localhost:30172"
   msg_broker_user: "" #"fbk_user"
   msg_broker_password: "" #@mqpt1m"
   send_topic: "TO_CARS" # msg_broker send topic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ .Release.Name }}
  template:
    metadata:
      labels:
        run: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
        name: {{ .Chart.Name }}
        env:
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-www-data
                key: api_port
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-www-data
                key: log_level
          - name: LOGGER_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-www-data
                key: logger_name
          - name: MSG_BROKER_ADDR_ONE
            value: {{ .Values.msgbrokerep_one}}
          - name: MSG_BROKER_ADDR_TWO
            value: {{ .Values.msgbrokerep_two}}
          - name: MSG_BROKER_USER
            value: {{ .Values.msgbrokeruser}}
          - name: MSG_BROKER_PASSWORD
            value: {{ .Values.msgbrokerpwd}}
          - name: SEND_TOPIC
            value: {{ .Values.sendtopic}}
        resources: {}
        imagePullPolicy: {{ .Values.image.pullPolicy}}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: {{ .Values.service.protocol}}
    targetPort: {{ .Values.service.port}}
    nodePort: {{ .Values.nodePort}}
  selector:
    run: {{ .Release.Name }}
  type: {{ .Values.service.type}}
status:
  loadBalancer: {}
