apiVersion: v1
kind: ConfigMap
metadata:
  name: main-manager-cm
  namespace: {{ .Values.namespace }}
data:
   logger_name: " Main Manager " # name as per need
   log_level:  "DEBUG"
   lm_config_json: "local_manager_config.json"
   log_path_general: "/logs/mm.log"
   log_path_timing: "/logs/mmtime.log"
   api_port: "4000" # port for API svc
   local_manager_post_address_one: "http://local-manager-service.default.svc.cluster.local:3500/api/item/from_main_mgr_config_api/1"
   #local_manager_post_address_two: "http://local-manager-2-service.clm-test.empower:3501/api/item/from_main_mgr_config_api/1"
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
    name: {{ .Chart.Name }}
    env:
      - name: LM_CONFIG_JSON
        valueFrom:
          configMapKeyRef:
            name: main-manager-cm
            key: lm_config_json
      - name: LOCAL_MANAGER_POST_ADDRESS_ONE
        valueFrom:
          configMapKeyRef:
            name: main-manager-cm
            key: local_manager_post_address_one
      #- name: LOCAL_MANAGER_POST_ADDRESS_TWO
      #  valueFrom:
      #    configMapKeyRef:
      #      name: main-manager-cm
      #      key: local_manager_post_address_two
      - name: API_PORT
        valueFrom:
          configMapKeyRef:
            name: main-manager-cm
            key: api_port
      - name: LOG_PATH_GENERAL
        valueFrom:
          configMapKeyRef:
            name: main-manager-cm
            key: log_path_general
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: main-manager-cm
            key: log_level
      - name: LOGGER_NAME
        valueFrom:
          configMapKeyRef:
            name: main-manager-cm
            key: logger_name
    resources: {}
    imagePullPolicy: {{ .Values.image.pullPolicy}}
    volumeMounts:
      - mountPath: "/logs/"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: log-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: {{ .Values.service.protocol}}
    targetPort: {{ .Values.service.port}}
    nodePort: {{ .Values.service.nodeport}}
  selector:
    run: {{ .Chart.Name }}
  type: {{ .Values.service.type}}
status:
  loadBalancer: {}
  type: {{ .Values.service.type}}
status:
  loadBalancer: {}
